[project]
requires-python = ">=3.10,<3.11"
dynamic = ["version"]
name = "pyda-dbi"

[build-system]
requires = [
    "setuptools>=64",
    "cmake>=3.18",
    "setuptools-scm>=8",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

