site_name: Pyda Documentation
site_description: Dynamic binary analysis tools using Python
site_url: https://ndrewh.github.io/pyda

repo_name: ndrewh/pyda
repo_url: https://github.com/ndrewh/pyda
docs_dir: pages

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../lib/]
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            docstring_style: google
            merge_init_into_class: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - API Reference:
    - Process: api/process.md
    - Exceptions: api/exceptions.md
  - Advanced Usage:
    - Attaching to a running process: advanced-usage/attaching.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true 
